### ISSUE TITLE
lru_cache makes things slower

### ISSUE THREAD

**Issue by timfel** [josephnavarro/pypy-raycaster#1]
At least on my machine, I'm seeing better performance on CPython, PyPy and GraalPython when the lru_cache annotations are removed. CPython improves only a little (~10%), but PyPy and GraalPython get around 60-70% faster for me.

**Comment by timfel** [comment]
Also, a general question: it seems the latest commits make everything slower on CPython, but faster on PyPy (and GraalPython). Is this meant to be a showcase for what can be done with a JIT or should the code also care about CPython performance? (asking because I'm thinking about contributing the odd thing or two)

**Comment by josephnavarro** [comment]
Hi, thanks for checking that part out. I'll remove the lru_cache annotations.

With regards to your general question, yes, this is meant to just focus on optimization for the JIT; I didn't really have the intention of having this run on CPython.

**Comment by timfel** [comment]
Thanks for the clarification!
